{% set version = "2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-limsolve
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/limSolve_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/limSolve/limSolve_{{ version }}.tar.gz
  sha256: 4009b4cd6852b393f3938457d0db55c79b3a9221cef72cf5dcbbdd9def4311bf

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-mass                       # [build_platform != target_platform]
    - r-lpsolve                    # [build_platform != target_platform]
    - r-quadprog                   # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-lpsolve
    - r-quadprog
  run:
    - r-base
    - r-mass
    - r-lpsolve
    - r-quadprog

test:
  commands:
    - $R -e "library('limSolve')"           # [not win]
    - "\"%R%\" -e \"library('limSolve')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=limSolve
  license: GPL-2.0-or-later
  summary: 'Functions that (1) find the minimum/maximum of a linear or quadratic function: min or max (f(x)), where f(x) = ||Ax-b||^2 or f(x) = sum(a_i*x_i) subject to equality constraints Ex=f and/or inequality constraints Gx>=h, (2) sample an underdetermined- or overdetermined system Ex=f subject to Gx>=h, and if applicable
    Ax~=b,       (3) solve a linear system Ax=B for the unknown x. It includes banded and tridiagonal linear systems.  The package calls Fortran functions from ''LINPACK''.'
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
