appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ExYjH/qi/aIYmBsvQWSW0P8VPVHNhDxxcXlRvEe9FFd39cKkjtIgmRRlWzxN1YQOu/eEOV4bvLaB36vCI5bmGja8372RMERtpZi8yPk5MLcQsG3bvIlbnYeeib5qGqbisEERjAh9nRH8iMuFp0G49n8OnFbllW48OW71phmSyn2gKSRawWLdZY4Mrfb9ebP5ha0qForDuouDq4NRP3wcOt7EaOOqnXKRxoSgCAm7gYT1893+u2jjM0GaPmWkduzjWWEI9RgWGwfwCVs4d+VDQp02RQHNApbwQJRuapASw/cb8wZdS0Ri6b/mBw0o6z6OdAgEBs4wVSunobWylusHzwDvwhYqFtomzo37vihiLFQK9H57oCAcJyOxIIR5cVGAQ3ib+ZccAU6aoOwayOowoEWZ+ua1QdKiZK3utHzA7TijJAnd1TZ0Gltl2uSaG0mEfC+iTY48SFTPiRjtgnigfbYseZk/nfz7W3xIIxMx/sfUGuRiZu0773au9k1PJxVc5p+igWgfwg0vSywfcK+QpFy8vUxoFZTHTD5U9HRCDCPNePMdz1pa+C+G9J1NDfGZVyc0oKa21Td6kACwS+nZzckB1X/oS6gffspAtY4XjDTy5ud2BiOcAN0D1JnQhgFB9/3WS9rQSgdk7DE0IPysGF7uVnHpcQ/54zUAVdMxOPc=}
bot:
  automerge: true
